spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: update
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
          show_sql: false

#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sbackjung
#    password:
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#    jpa:
#      defer-datasource-initialization: true
#      database-platform: H2
#      hibernate:
#        ddl-auto: create-drop
#      open-in-view: false
#      properties:
#        hibernate:
#          format_sql: true
#          show_sql: false