spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    post: 587
    username: tlarbdnjs3011@gmail.com
    password: zdpmavtncvomhcdo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET_KEY}
            redirect-uri: ${NAVER_REDIRECT_URL}
            authorization-grant-type: authorization_code
            scope: email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha  # Swagger UI에서 알파벳 순으로 정렬
      tags-sorter: alpha  # 태그 알파벳 순 정렬
      disable-swagger-default-url: true
      display-query-params-without-oauth2: true
      doc-expansion: none

    api-docs:
      path: /api-docs  # OpenAPI JSON 문서 확인 경로

    default-consumes-media-type: application/json  # 기본 요청 컨텐츠 타입 설정
    default-produces-media-type: application/json  # 기본 응답 컨텐츠 타입 설정
  jwt:
    secret: ${JWT_SECRET_KEY}


  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  main:
    allow-bean-definition-overriding: true
