name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  # 나중에 main 브랜치로 변경 예정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub 저장소에서 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3  # 최신 버전 사용

      # JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3  # 최신 버전 사용
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 캐시 적용 (빌드 최적화)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Gradle Wrapper 실행 권한 부여
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      # Gradle 빌드 실행 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew build -x test  # 테스트 제외하고 빌드

      # 빌드된 JAR 파일에 실행 권한 부여
      - name: Grant execute permission for JAR
        run: chmod +x build/libs/TransferStay-0.0.1-SNAPSHOT.jar

      # 권한이 부여된 JAR 파일을 EC2로 복사
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.0  # 버전 명시
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: build/libs/TransferStay-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - Updated CD Script for GitHub Actions

      - name: EC2에 SSH 연결 후 JAR 실행
      - uses: appleboy/ssh-action@v0.1.0
      - with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -x  # 디버그 모드 활성화
            cd /home/ubuntu/
            source ~/.bash_profile
            echo "현재 디렉토리: $(pwd)"
            echo "Java 버전: $(java -version)"

            # JAR 파일 경로 설정
            JAR_PATH="/home/ubuntu/build/libs/TransferStay-0.0.1-SNAPSHOT.jar"
  
            # 기존 JAR 프로세스 종료
            echo "기존 애플리케이션 종료 중..."
            pkill -f 'TransferStay-0.0.1-SNAPSHOT.jar' || true
  
            # 기존 프로세스 종료 확인
            if pgrep -f 'TransferStay-0.0.1-SNAPSHOT.jar'; then
              echo "이전 프로세스가 아직 실행 중입니다. 강제 종료합니다."
              pkill -9 -f 'TransferStay-0.0.1-SNAPSHOT.jar'
            else
              echo "실행 중인 이전 프로세스가 없습니다."
            fi
  
            # 새로운 JAR 파일 실행 및 로그 저장
            echo "새로운 애플리케이션 시작 중..."
            if [ -f "$JAR_PATH" ]; then
              chmod +x "$JAR_PATH"
              nohup java -jar "$JAR_PATH" > app.log 2>&1 &
            else
              echo "JAR 파일을 $JAR_PATH 에서 찾을 수 없습니다!"
              exit 1
            fi
  
            # 프로세스 시작 확인
            sleep 10
            if pgrep -f 'TransferStay-0.0.1-SNAPSHOT.jar'; then
              echo "새 프로세스가 성공적으로 시작되었습니다."
              echo "프로세스 세부 정보:"
              ps aux | grep 'TransferStay-0.0.1-SNAPSHOT.jar'
            
            else
              echo "새 프로세스 시작에 실패했습니다."
              echo "app.log 파일의 내용:"
              tail -n 50 app.log
              exit 1
            fi