name: Display Secrets

on:
  push:
    branches:
      - develop  # develop 브랜치에 푸시할 때 실행

jobs:
  show-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Secret Values
        run: |
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER: ${{ secrets.EC2_USER }}"
          echo "EC2_KEY: ${{ secrets.EC2_KEY }}"
